server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
